extraction: 
  cpp:
    prepare:
      packages:
        - cmake
        - build-essential
        - g++-6
    configure:
      command:
        - mkdir build
        - cd build
        - cmake ..
    index:
      build_command:
        - cd build
        - make