extraction: 
  cpp:
    prepare:
      packages:
        - cmake
    configure:
      command:
        - mkdir build
        - cd build
        - cmake ..
    index:
      build_command:
        - cd build
        - make